### ISSUE TITLE
ROFS extractor get stucks at 50% with any rofs file

### ISSUE THREAD

**Issue by elmarsan** [temmieheartz/R3ditor-V2#21]

**Comment by themitosan** [comment]
Hello @elmarsan, doing fine?
Can you tell more details about how this issue is happening?

Also: Before we move on, open `Tools/rofs.exe` on `cmd` and see if it gives any kind of error.

**Comment by elmarsan** [comment]
Hey @themitosan.

By using the UI every time I try to use the ROFS extractor the load bar gets stuck in 50%.

![imagen](https://github.com/themitosan/R3ditor-V2/assets/43180519/58039a92-706a-4253-a91f-3d940dee206a)

![imagen](https://github.com/themitosan/R3ditor-V2/assets/43180519/f54a42fb-d9bd-4e76-bc5d-5040d153320c)

However using `Tools/rofs.exe` works perfect.

**Comment by themitosan** [comment]
I see... Does something shows up on console / log?

**Comment by themitosan** [comment]
Since this issue didn't get any answers, I will keep it closed until new developments.
